spring:  datasource:    url: jdbc:mysql://localhost:3306/elearningdb    username: root
    password: admin
  jpa:    hibernate:      ddl-auto: none      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
eureka:  instance:    instance-id: ${spring.application.name}-${random.int}